Update testHelpers.js
TooAngel/screeps pull request #615
Opened 2020-10-16 20:20 UTC by pieterbrandsen

Small read update, I think myself it's better/cleaner in this way.

If you look at the other cases mostly it's done in this way instead of '+'.

2020-10-16 20:33 UTC, TooAngel requested changes

2020-10-16 20:33 UTC, TooAngel commented on utils/testHelpers.js
> +      console.log($`> Spawn bot ${room} as TooAngel`);
```suggestion
      console.log(`> Spawn bot ${room} as TooAngel`);
```

2020-10-16 21:01 UTC, TooAngel approved these changes
Thx, for fixing it :-)

If you squash your commits to a single one it will get merged quite faster.

2020-10-16 21:39 UTC, pieterbrandsen commented
No problem

2020-10-24 16:34 UTC, merged

2020-10-24 16:34 UTC, TooAngel commented
This pull request was merged by [worlddriven](https://www.worlddriven.org).